### ISSUE TITLE
Create meetup organizer submission process 

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#190]
Agree with the Ansible community on meetup organizer submission process and permission to use community meetup resources and access to things like the calendar and shoutout zone. (community working group)

**Comment by anweshadas** [comment]
Community can collaborate on the Meetup Toolkit in the following ways   

1. Recognizing people at Shoutout Zone
2. Sharing presentation templates 
3. Sharing social media post templates 
4. Sharing communication(email/message) templates 
5. Sharing the event details in Calendar
6. Sharing feedback of the event in the form of blog posts
7. Sharing talk ideas
8. Sharing blog posts
9. Sharing community voice in general

Now since we are envisioning this Toolkit to be a part of our new Ansible Community Website should  we use https://github.com/ansible-community/community-website ? Create a new branch a 'Meetup Toolkit' over there and work on that? @oraNod @cybette @leogallego what do you all think?

**Comment by samccann** [comment]
yeah makes sense to move it. Let's see if anyone disagrees before we do that. Github lets us transfer the issue to the other repo easily enuf.

**Comment by cybette** [comment]
+1 move to community-website

**Comment by cybette** [comment]
Discussion on where to put the toolkit: https://forum.ansible.com/t/where-should-we-source-and-publish-toolkits-for-projects/43

For "meetup organizer submission process", the meetupbot is taking care of most of it. As long as the organizer creates a meetup event in a group that we're tracking, it will show up on the forum's [Events category and calendar](https://forum.ansible.com/c/events/8).

**Comment by leogallego** [comment]
Resurfacing this as we need to review the location of the meetup toolkit.

**Comment by samccann** [comment]
Rather than reopening an old epic, can you open a new issue here and assign to yourself?
