### ISSUE TITLE
Investigate Diataxis framework

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#233]
Relates to https://github.com/ansible-community/community-team/issues/230

Investigate [Diataxis framework](https://diataxis.fr/how-to-guides/), write and discuss a summary of things we should apply

**Comment by Andersson007** [comment]
Conclusion: The framework is a very good document that confirms my intuitive feelings about how-to's and provides valuable practical recommendations.

My original plan was:
- Create overview pages for EE itself and for each component that will provide the context and explanations for unfamiliar people
- They will refer to related tutorials/how to's for each tool

After reading the framework, i think after creating overview pages:
1. we could try to write a comprehensive set of how-to's for each tool
2. then we'll try to write a comprehensive tutorial for each tool (if needed; maybe the overview pages will be enough and how-to's will do the rest)
3. create a separate page listing all EE related how-to's

Any feedback on the framework and the comment would be much appreciated.

**Comment by Andersson007** [comment]
@oraNod @samccann what do you think on the chosen strategy ^ ?

**Comment by oraNod** [comment]
@Andersson007 Glad to hear you think the Diataxis framework is useful and confirms your initial approach.

My 2c is that we focus the how-to's on personas and specific objectives, rather than "each tool". I think when we talk about framing docs around a tool it puts the focus on the technology moreso than the user objectives.

All the how-to's should be contained within the package docs and span multiple projects in the ecosystem: core, builder, awx, etc.

For tutorials my thinking is that they should belong as part of the respective project docs and contain details like installation and configuration. In this way, tutorials and reference are more specific to the technology. It doesn't need to be a hard line or anything though.

I think the chosen strategy is a good one at any rate. Big +1 from me. We really need more of those comprehensive how-tos!

**Comment by Andersson007** [comment]
@oraNod thanks for the feedback! Closing as done
